 export const deposits = [
  {
    id: "107",
    termType: "FixedTerm",
    termLengthUnit: "Month",
    termLength: 6,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "5",
      isFscsProtected: true,
      isSharia: true,
      name: "Barclays",
      shortName: "BRC",
      countryCode: "IMN",
      inidicationColour: "#00aeef",
      logoUri: null,
      fitchRating: "A",
      hasRingfencingEnabled: true,
      creditUnion: true,
      fscsGroupId: "1",
    },
    currencyCode: "GBP",
    interestPaidType: "AtMaturity",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Month",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2023-04-26T13:44:40Z",
    productIssues: [
      {
        tAndCs: {
          id: "173",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/107/issue/1/version/3/document/ProductTermsAndConditions",
        },
        issueNumber: 1,
        issueVersionNumber: 3,
        isClosedToNewClients: false,
        ratePercent: -61.41,
        aer: -51.98,
        depositPerClientMinimum: 2,
        depositPerClientMaximum: 456,
        createdDateTimeUtc: "2024-10-28T14:33:10Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "68",
    termType: "FixedTerm",
    termLengthUnit: "Month",
    termLength: 2,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "3",
      isFscsProtected: false,
      isSharia: false,
      name: "Investec",
      shortName: "INV",
      countryCode: "GBR",
      inidicationColour: "#000F48",
      logoUri: "https://staticassets.flagstoneim.com/Logos/Banks/Investec.svg",
      fitchRating: "BBBPlus",
      hasRingfencingEnabled: true,
      creditUnion: false,
      fscsGroupId: null,
    },
    currencyCode: "GBP",
    interestPaidType: "AtMaturity",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Month",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2023-01-19T10:35:56Z",
    productIssues: [
      {
        tAndCs: {
          id: "86",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/68/issue/1/version/1/document/ProductTermsAndConditions",
        },
        issueNumber: 1,
        issueVersionNumber: 1,
        isClosedToNewClients: false,
        ratePercent: -0.01,
        aer: 0.0,
        depositPerClientMinimum: 2,
        depositPerClientMaximum: 1000000,
        createdDateTimeUtc: "2023-01-05T09:52:26Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "29",
    termType: "InstantAccess",
    termLengthUnit: "NoTerm",
    termLength: 0,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "3",
      isFscsProtected: false,
      isSharia: false,
      name: "Investec",
      shortName: "INV",
      countryCode: "GBR",
      inidicationColour: "#000F48",
      logoUri: "https://staticassets.flagstoneim.com/Logos/Banks/Investec.svg",
      fitchRating: "BBBPlus",
      hasRingfencingEnabled: true,
      creditUnion: false,
      fscsGroupId: null,
    },
    currencyCode: "GBP",
    interestPaidType: "Daily",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Daily",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2023-04-03T16:11:12Z",
    productIssues: [
      {
        tAndCs: {
          id: "237",
          version: 4,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/29/issue/1/version/2/document/ProductTermsAndConditions",
        },
        issueNumber: 1,
        issueVersionNumber: 2,
        isClosedToNewClients: false,
        ratePercent: 0.1,
        aer: 0.1,
        depositPerClientMinimum: 2,
        depositPerClientMaximum: 1000000,
        createdDateTimeUtc: "2023-06-12T07:40:07Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "108",
    termType: "FixedTerm",
    termLengthUnit: "Month",
    termLength: 6,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "3",
      isFscsProtected: false,
      isSharia: false,
      name: "Investec",
      shortName: "INV",
      countryCode: "GBR",
      inidicationColour: "#000F48",
      logoUri: "https://staticassets.flagstoneim.com/Logos/Banks/Investec.svg",
      fitchRating: "BBBPlus",
      hasRingfencingEnabled: true,
      creditUnion: false,
      fscsGroupId: null,
    },
    currencyCode: "GBP",
    interestPaidType: "AtMaturity",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Month",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2023-04-26T13:48:07Z",
    productIssues: [
      {
        tAndCs: {
          id: "176",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/108/issue/1/version/12/document/ProductTermsAndConditions",
        },
        issueNumber: 1,
        issueVersionNumber: 12,
        isClosedToNewClients: false,
        ratePercent: 0.19,
        aer: 0.19,
        depositPerClientMinimum: 3,
        depositPerClientMaximum: 357,
        createdDateTimeUtc: "2024-09-30T10:50:12Z",
      },
    ],
    isTopRate: true,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "131",
    termType: "FixedTerm",
    termLengthUnit: "Day",
    termLength: 1,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "4",
      isFscsProtected: false,
      isSharia: false,
      name: "Modelo Bank",
      shortName: "MLO",
      countryCode: "GBR",
      inidicationColour: "#42d7f5",
      logoUri: "https://staticassets.flagstoneim.com/Logos/Banks/Modelo.png",
      fitchRating: "CPlus",
      hasRingfencingEnabled: false,
      creditUnion: false,
      fscsGroupId: null,
    },
    currencyCode: "GBP",
    interestPaidType: "Daily",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Daily",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2023-05-25T08:08:55Z",
    productIssues: [
      {
        tAndCs: {
          id: "251",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/131/issue/1/version/16/document/ProductTermsAndConditions",
        },
        issueNumber: 1,
        issueVersionNumber: 16,
        isClosedToNewClients: false,
        ratePercent: 0.21,
        aer: 0.21,
        depositPerClientMinimum: 1,
        depositPerClientMaximum: 100000,
        createdDateTimeUtc: "2023-10-25T11:40:51Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "19",
    termType: "InstantAccess",
    termLengthUnit: "NoTerm",
    termLength: 0,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "3",
      isFscsProtected: false,
      isSharia: false,
      name: "Investec",
      shortName: "INV",
      countryCode: "GBR",
      inidicationColour: "#000F48",
      logoUri: "https://staticassets.flagstoneim.com/Logos/Banks/Investec.svg",
      fitchRating: "BBBPlus",
      hasRingfencingEnabled: true,
      creditUnion: false,
      fscsGroupId: null,
    },
    currencyCode: "GBP",
    interestPaidType: "Daily",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Daily",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2023-07-25T10:37:53Z",
    productIssues: [
      {
        tAndCs: {
          id: "13",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/19/issue/3/version/10/document/ProductTermsAndConditions",
        },
        issueNumber: 3,
        issueVersionNumber: 10,
        isClosedToNewClients: false,
        ratePercent: 0.224,
        aer: 0.22,
        depositPerClientMinimum: 100,
        depositPerClientMaximum: 1000000,
        createdDateTimeUtc: "2024-10-28T08:14:41Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "32",
    termType: "InstantAccess",
    termLengthUnit: "NoTerm",
    termLength: 0,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "3",
      isFscsProtected: false,
      isSharia: false,
      name: "Investec",
      shortName: "INV",
      countryCode: "GBR",
      inidicationColour: "#000F48",
      logoUri: "https://staticassets.flagstoneim.com/Logos/Banks/Investec.svg",
      fitchRating: "BBBPlus",
      hasRingfencingEnabled: true,
      creditUnion: false,
      fscsGroupId: null,
    },
    currencyCode: "GBP",
    interestPaidType: "Daily",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Daily",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2023-04-03T10:02:48Z",
    productIssues: [
      {
        tAndCs: {
          id: "35",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/32/issue/2/version/1/document/ProductTermsAndConditions",
        },
        issueNumber: 2,
        issueVersionNumber: 1,
        isClosedToNewClients: false,
        ratePercent: 0.26,
        aer: 0.26,
        depositPerClientMinimum: 100,
        depositPerClientMaximum: 5000000,
        createdDateTimeUtc: "2022-08-03T09:36:30Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "34",
    termType: "Notice",
    termLengthUnit: "NoTerm",
    termLength: 0,
    noticeLengthUnit: "Month",
    noticeLength: 1,
    financialInstitution: {
      id: "7",
      isFscsProtected: true,
      isSharia: true,
      name: "National Westminster Bank",
      shortName: "NAT",
      countryCode: "GBR",
      inidicationColour: "#fff",
      logoUri: "https://staticassets.flagstoneim.com/Logos/Banks/Natwest.png",
      fitchRating: "NotAvailable",
      hasRingfencingEnabled: true,
      creditUnion: false,
      fscsGroupId: "4",
    },
    currencyCode: "GBP",
    interestPaidType: "Variable",
    interestPaysPlan: "FirstOf",
    interestPaysFrequency: "Month",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2024-03-01T15:44:35Z",
    productIssues: [
      {
        tAndCs: {
          id: "38",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/34/issue/2/version/1/document/ProductTermsAndConditions",
        },
        issueNumber: 2,
        issueVersionNumber: 1,
        isClosedToNewClients: false,
        ratePercent: 0.32,
        aer: 0.32,
        depositPerClientMinimum: 34,
        depositPerClientMaximum: 85000,
        createdDateTimeUtc: "2024-03-01T15:44:35Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "60",
    termType: "Notice",
    termLengthUnit: "NoTerm",
    termLength: 0,
    noticeLengthUnit: "Day",
    noticeLength: 20,
    financialInstitution: {
      id: "1",
      isFscsProtected: true,
      isSharia: false,
      name: "Modelo Butterfield Bank",
      shortName: "_=-",
      countryCode: "GBR",
      inidicationColour: "#FFA500",
      logoUri:
        "https://staticassets.flagstoneim.com/Logos/Banks/Butterfield.svg",
      fitchRating: "NotAvailable",
      hasRingfencingEnabled: true,
      creditUnion: false,
      fscsGroupId: "1",
    },
    currencyCode: "GBP",
    interestPaidType: "Daily",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Daily",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2022-11-22T16:28:09Z",
    productIssues: [
      {
        tAndCs: {
          id: "79",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/60/issue/1/version/1/document/ProductTermsAndConditions",
        },
        issueNumber: 1,
        issueVersionNumber: 1,
        isClosedToNewClients: false,
        ratePercent: 0.99,
        aer: 0.99,
        depositPerClientMinimum: 1000,
        depositPerClientMaximum: 85000,
        createdDateTimeUtc: "2022-11-22T16:28:00Z",
      },
    ],
    isTopRate: true,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "96",
    termType: "InstantAccess",
    termLengthUnit: "NoTerm",
    termLength: 0,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "1",
      isFscsProtected: true,
      isSharia: false,
      name: "Modelo Butterfield Bank",
      shortName: "_=-",
      countryCode: "GBR",
      inidicationColour: "#FFA500",
      logoUri:
        "https://staticassets.flagstoneim.com/Logos/Banks/Butterfield.svg",
      fitchRating: "NotAvailable",
      hasRingfencingEnabled: true,
      creditUnion: false,
      fscsGroupId: "1",
    },
    currencyCode: "GBP",
    interestPaidType: "Daily",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Daily",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2023-02-27T14:57:08Z",
    productIssues: [
      {
        tAndCs: {
          id: "132",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/96/issue/1/version/1/document/ProductTermsAndConditions",
        },
        issueNumber: 1,
        issueVersionNumber: 1,
        isClosedToNewClients: false,
        ratePercent: 1.09,
        aer: 1.09,
        depositPerClientMinimum: 1,
        depositPerClientMaximum: 10000,
        createdDateTimeUtc: "2023-02-27T14:56:33Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "24",
    termType: "InstantAccess",
    termLengthUnit: "NoTerm",
    termLength: 0,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "5",
      isFscsProtected: true,
      isSharia: true,
      name: "Barclays",
      shortName: "BRC",
      countryCode: "IMN",
      inidicationColour: "#00aeef",
      logoUri: null,
      fitchRating: "A",
      hasRingfencingEnabled: true,
      creditUnion: true,
      fscsGroupId: "1",
    },
    currencyCode: "GBP",
    interestPaidType: "Daily",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Daily",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2023-04-04T15:45:58Z",
    productIssues: [
      {
        tAndCs: {
          id: "19",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/24/issue/1/version/5/document/ProductTermsAndConditions",
        },
        issueNumber: 1,
        issueVersionNumber: 5,
        isClosedToNewClients: false,
        ratePercent: 1.19,
        aer: 1.19,
        depositPerClientMinimum: 100,
        depositPerClientMaximum: 300,
        createdDateTimeUtc: "2024-07-02T17:34:07Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "11",
    termType: "FixedTerm",
    termLengthUnit: "Year",
    termLength: 1,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "2",
      isFscsProtected: true,
      isSharia: true,
      name: "Aldermore Bank",
      shortName: "ALD",
      countryCode: "GBR",
      inidicationColour: "#E5BB07",
      logoUri: "https://staticassets.flagstoneim.com/Logos/Banks/Aldermore.svg",
      fitchRating: "BBBPlus",
      hasRingfencingEnabled: true,
      creditUnion: true,
      fscsGroupId: "1",
    },
    currencyCode: "GBP",
    interestPaidType: "Daily",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Daily",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2023-05-26T11:32:32Z",
    productIssues: [
      {
        tAndCs: {
          id: "133",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/11/issue/5/version/3/document/ProductTermsAndConditions",
        },
        issueNumber: 5,
        issueVersionNumber: 3,
        isClosedToNewClients: false,
        ratePercent: 1.21,
        aer: 1.21,
        depositPerClientMinimum: 35000,
        depositPerClientMaximum: 43000,
        createdDateTimeUtc: "2023-03-29T11:04:39Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "180",
    termType: "FixedTerm",
    termLengthUnit: "Year",
    termLength: 1,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "1",
      isFscsProtected: true,
      isSharia: false,
      name: "Modelo Butterfield Bank",
      shortName: "_=-",
      countryCode: "GBR",
      inidicationColour: "#FFA500",
      logoUri:
        "https://staticassets.flagstoneim.com/Logos/Banks/Butterfield.svg",
      fitchRating: "NotAvailable",
      hasRingfencingEnabled: true,
      creditUnion: false,
      fscsGroupId: "1",
    },
    currencyCode: "GBP",
    interestPaidType: "Anniversary",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Year",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2024-05-30T12:46:27Z",
    productIssues: [
      {
        tAndCs: {
          id: "308",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/180/issue/1/version/1/document/ProductTermsAndConditions",
        },
        issueNumber: 1,
        issueVersionNumber: 1,
        isClosedToNewClients: false,
        ratePercent: 1.22,
        aer: 1.22,
        depositPerClientMinimum: 1000,
        depositPerClientMaximum: 10000,
        createdDateTimeUtc: "2024-05-30T12:46:05Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "181",
    termType: "FixedTerm",
    termLengthUnit: "Year",
    termLength: 1,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "1",
      isFscsProtected: true,
      isSharia: false,
      name: "Modelo Butterfield Bank",
      shortName: "_=-",
      countryCode: "GBR",
      inidicationColour: "#FFA500",
      logoUri:
        "https://staticassets.flagstoneim.com/Logos/Banks/Butterfield.svg",
      fitchRating: "NotAvailable",
      hasRingfencingEnabled: true,
      creditUnion: false,
      fscsGroupId: "1",
    },
    currencyCode: "GBP",
    interestPaidType: "Anniversary",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Year",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2024-05-30T12:48:26Z",
    productIssues: [
      {
        tAndCs: {
          id: "309",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/181/issue/1/version/1/document/ProductTermsAndConditions",
        },
        issueNumber: 1,
        issueVersionNumber: 1,
        isClosedToNewClients: false,
        ratePercent: 1.22,
        aer: 1.22,
        depositPerClientMinimum: 1000,
        depositPerClientMaximum: 10000,
        createdDateTimeUtc: "2024-05-30T12:47:51Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "153",
    termType: "FixedTerm",
    termLengthUnit: "Month",
    termLength: 12,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "2",
      isFscsProtected: true,
      isSharia: true,
      name: "Aldermore Bank",
      shortName: "ALD",
      countryCode: "GBR",
      inidicationColour: "#E5BB07",
      logoUri: "https://staticassets.flagstoneim.com/Logos/Banks/Aldermore.svg",
      fitchRating: "BBBPlus",
      hasRingfencingEnabled: true,
      creditUnion: true,
      fscsGroupId: "1",
    },
    currencyCode: "GBP",
    interestPaidType: "AtMaturity",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Month",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2024-02-22T06:58:46Z",
    productIssues: [
      {
        tAndCs: {
          id: "294",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/153/issue/1/version/3/document/ProductTermsAndConditions",
        },
        issueNumber: 1,
        issueVersionNumber: 3,
        isClosedToNewClients: false,
        ratePercent: 1.29,
        aer: 1.29,
        depositPerClientMinimum: 10000,
        depositPerClientMaximum: 85000,
        createdDateTimeUtc: "2024-03-04T14:51:18Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
  {
    id: "23",
    termType: "InstantAccess",
    termLengthUnit: "NoTerm",
    termLength: 0,
    noticeLengthUnit: "NoNotice",
    noticeLength: 0,
    financialInstitution: {
      id: "3",
      isFscsProtected: false,
      isSharia: false,
      name: "Investec",
      shortName: "INV",
      countryCode: "GBR",
      inidicationColour: "#000F48",
      logoUri: "https://staticassets.flagstoneim.com/Logos/Banks/Investec.svg",
      fitchRating: "BBBPlus",
      hasRingfencingEnabled: true,
      creditUnion: false,
      fscsGroupId: null,
    },
    currencyCode: "GBP",
    interestPaidType: "Daily",
    interestPaysPlan: "NoPaysPlan",
    interestPaysFrequency: "Daily",
    interestPaysSpecificDates: [],
    dateLastUpdatedUTC: "2023-07-18T13:03:56Z",
    productIssues: [
      {
        tAndCs: {
          id: "17",
          version: 1,
          documentType: "ProductTermsAndConditions",
          contentTypes: ["application/pdf"],
          uri: "fim-forlocal-cdp-tx-api-uks.fimdevelopmentuks.appserviceenvironment.net/products/23/issue/3/version/3/document/ProductTermsAndConditions",
        },
        issueNumber: 3,
        issueVersionNumber: 3,
        isClosedToNewClients: false,
        ratePercent: 1.59,
        aer: 1.6,
        depositPerClientMinimum: 9,
        depositPerClientMaximum: 85000,
        createdDateTimeUtc: "2023-09-11T12:20:49Z",
      },
    ],
    isTopRate: false,
    isNonPooled: false,
    eligibleProductIssue: null,
  },
];
